// aprendiendo-vue/src/components/Pelicula.vue
<template>
    <article class="article-item">
        <div class="image-wrap">
          <img :src="pelicula.image" :alt="pelicula.title" />
        </div>

        <h2>{{pelicula.title}}</h2>
        <span class="date" :class="{
            yeargreen: pelicula.year >= 2005,
            yearred: pelicula.year < 2005
        }">{{pelicula.year}}</span>
        <a href="#">Leer más</a>
        <input type="button" value="Marcar como favorita" @click="marcarComoFavorita(pelicula)"/>
        <div class="clearfix"></div>
      </article>
</template>

<script>
export default {
    name:"Pelicula",
    props: ['pelicula'],
    methods: {
      marcarComoFavorita(pelicula){
        this.$emit("favorita", pelicula);
      }
    }
}
</script>

// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() pelicula: Pelicula;
  @Output() marcarFavorita = new EventEmitter();

  constructor() { }

  ngOnInit() {
  }

  marcarComoFavorita(event, pelicula){
    this.marcarFavorita.emit(pelicula);
  }

}

<article class="article-item" id="article-template">
    <div class="image-wrap">
        <img src="{{pelicula.image}}" alt="{{pelicula.title}}">
    </div>

    <h2>{{pelicula.title}}</h2>
    <span class="year"
        [ngClass]="{'year-green': pelicula.year > 2016, 'year-red': pelicula.year <= 2016}">{{pelicula.year}}</span>
    <a href="#">Leer más</a>
    <button (click)="marcarComoFavorita($event, pelicula)">Seleccionar como favorita</button>
    <div class="clearfix"></div>
</article>
