// aprendiendo-vue/src/components/Articles.vue
<template>
  <div id="list-articles">
    <article class="article-item" v-for="article in articles" v-bind:key="article._id">
      <div class="image-wrap">
        <img :src="url +'get-image/' + article.image" :alt="article.title" v-if="article.image" />
        <img src="../assets/images/default.png" :alt="article.title" v-if="!article.image" />
      </div>

     <h2> <router-link :to="{name: 'article', params: {id: article._id}}"> {{article.title}} </router-link></h2>
      <span class="date">{{article.date | moment("from", "now") | capitalize}}</span>
      <router-link :to="{name: 'article', params: {id: article._id}}">Leer más</router-link>
      <div class="clearfix"></div>
    </article>
  </div>
</template>

<script>
import Global from '../Global'
export default {
  name: "Articles",
  props: ["articles"],
  data (){
      return {
          url: Global.url
      }
  },
  filters: {
    capitalize(value) {
      return value.charAt(0).toUpperCase() + value.slice(1);
    }
  }
};
</script>

// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Articulo } from 'src/app/models/articulo';
import { Global } from 'src/app/services/global';


@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  @Input() articles: Articulo[];
  public url: string;
  constructor() { 
    this.url = Global.url;
  }

  ngOnInit() {
  }

}

<div class="loading" *ngIf="!articles">
    Cargando...
</div>
<div id="articles" *ngIf="articles">
    <article class="article-item" *ngFor="let article of articles">
        <div class="image-wrap">
            <img src="{{url + 'get-image/' +article.image}}" alt="{{article.title}}" *ngIf="article.image">
            <img src="assets/images/default.png" alt="{{article.title}}" *ngIf="!article.image">
        </div>

        <h2>{{article.title}}</h2>
        <span class="date">{{article.date | amLocale: 'es' | amTimeAgo }}</span>
        <a [routerLink]="['/blog/article', article._id]">Leer más</a>
        <div class="clearfix"></div>
    </article>
</div>
