// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Articulo } from 'src/app/models/articulo';
import { ArticuloService } from 'src/app/services/articulo.service';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from 'src/app/services/global';
import swal from 'sweetalert';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticuloService]
})
export class ArticleComponent implements OnInit {

  public article: Articulo;
  public url: string;
  constructor(
    private _articuloService: ArticuloService,
    private _router: Router,
    private _route: ActivatedRoute
  ) {
    this.url = Global.url;
  }

  ngOnInit() {
    this._route.params.subscribe(
      params => {
        let id = params['id'];

        this._articuloService.getArticle(id).subscribe(
          response => {
            if (response.article) {
              this.article = response.article;
            } else {
              this._router.navigate(['/home']);
            }
          },
          error => {
            console.log(error);
          }
        )
      }
    )
  }

  delete(id) {
    swal({
      title: "¿Estás seguro?",
      text: "Una vez borrado el articulo, no podras recuperarlo",
      icon: "warning",
      buttons: [true, true],
      dangerMode: true
    })
      .then((willDelete) => {
        if (willDelete) {

          this._articuloService.deleteArticle(id).subscribe(
            response => {
              if (response.status = "Success") {
                swal("El articulo se ha eliminado", {
                  icon: "success",
                });
                this._router.navigate(['/blog']);
              }
            },
            error => {
              swal("El articulo no se ha eliminado", {
              icon: "error",
            });
              this._router.navigate(['/blog']);
            }
          )
        } else {
          swal("El articulo no se ha eliminado");
        }
      });
  }

}

<app-slider [nombre]="'BLOG'" [size] = "'small'"></app-slider>

<div class="center">
    
    <section id="content">
        <article class="article-item article-detail" *ngIf="article">
            <div class="image-wrap">
                <img src="{{url + 'get-image/'+ article.image}}" alt="{{article.title}}">
            </div>

            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">{{article.date | amLocale: 'es' | amTimeAgo}}</span>
            <p>
                {{article.content}}
            </p>
            <div class="buttons">
                <a class="btn btn-warning" [routerLink]="['/blog/edit', article._id]">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a></div>
            <div class="clearfix"></div>
        </article>
    </section>
    <app-sidebar></app-sidebar>
</div>

// aprendiendo-vue/src/components/Article.vue
<template>
  <div id="general">
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" v-if="article">
          <div class="image-wrap" v-if="article.image">
            <img :src="url + 'get-image/' + article.image" :alt="article.title" />
          </div>

          <h1 class="subheader">{{article.title}}</h1>
          <span class="date">{{article.date | moment('from', 'now')}}</span>
          <p>{{article.content}}</p>

          <div class="clearfix"></div>

          <router-link :to="'/editar-articulo/' + article._id" class="btn btn-warning">Modificar</router-link>
          <a @click="deleteArticle(article._id)" class="btn btn-danger">Eliminar</a>
        </article>
      </section>
      <Sidebar></Sidebar>
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import Global from "../Global";
import Sidebar from "./Sidebar.vue";
import swal from "sweetalert";

export default {
  name: "Article",
  components: {
    Sidebar
  },
  data() {
    return {
      url: Global.url,
      article: null
    };
  },
  mounted() {
    var articleId = this.$route.params.id;
    this.getArticle(articleId);
  },
  methods: {
    getArticle(id) {
      axios.get(this.url + "article/" + id).then(res => {
        if (res.data.status == "Success") {
          this.article = res.data.article;
        }
      });
    },
    deleteArticle(id) {
      swal({
        title: "¿Estas seguro?",
        text: "Una vez eliminado el articulo no podrás recuperarlo",
        icon: "warning",
        buttons: true,
        dangerMode: true
      }).then(willDelete => {
        if (willDelete) {
          axios
            .delete(this.url + "article/" + id)
            .then(() => {
              swal(
                "Articulo Eliminado",
                "El articulo se ha eliminado correctamente",
                "success"
              );
              this.$router.push("/blog");
            })
            .catch(error => {
              swal("Error", "El articulo no ha podido ser eliminado", "error");
              console.log(error);
            });
        } else {
          swal("Articulo no eliminado");
        }
      });
    }
  }
};
</script>
