// AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params, Router } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public searchString: string;
  constructor(
    private _router: Router,
    private _route: ActivatedRoute
  ) { }

  ngOnInit() {
  }

  goSearch(){
    if(this.searchString != undefined){
      this._router.navigate(['/buscar', this.searchString]);
    }
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a href="#" class="btn btn-success" [routerLink]="['/blog/new']">Crear artículo</a>
    </div>
    <div id="nav-search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el articulo que buscas</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" #searchField="ngModel" [(ngModel)]="searchString" required>
            <small *ngIf="!searchField.valid && searchField.touched">El campo buscar esta vacio</small>
            <input type="submit" name="submit" value="Buscar" class="btn" [disabled]="!searchForm.valid">
        </form>
    </div>
</aside>

<div class="clearfix"></div>

// aprendiendo-vue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">Crear artículo</a>
    </div>
    <div id="nav-search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el articulo que buscas</p>
      <form action>
        <input type="text" name="search" />
        <input type="submit" name="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar"
};
</script>
