// aprendiendo-vue/src/components/Peliculas.vue
<template>
  <div id="general">
    <div class="center">
      <section id="content">
        <h1 class="subheader">Peliculas</h1>
        <h2 id="favorita" v-if="this.favorita">La pelicula favorita es: <strong>{{this.favorita.title}}</strong></h2>
        <div id="articles">
          <div v-for="pelicula in peliculasMayuscula" :key="pelicula.title">
            <Pelicula :pelicula="pelicula" 
            @favorita="mostrarFavorita"></Pelicula>
          </div>
        </div>
        <div class="misdatos">
          <p v-html="mostrarDatos"></p>
          <br/>
          <p> {{this.web | mayusculas | concatYear}}</p>
        </div>
      </section>
      <Sidebar></Sidebar>
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Pelicula from "./Pelicula.vue";

export default {
  name: "Peliculas",
  components: {
    Pelicula,
    Sidebar
  },
  data() {
    return {
      nombre: 'Rueskas',
      web: 'https://www.udemy.com/course/master-en-frameworks-javascript-aprende-angular-react-vue-js',
      favorita : null,
      peliculas: [
        {
          title: "Harry Potter",
          year: 2002,
          image: "https://i.ytimg.com/vi/CKt0PQFECfs/maxresdefault.jpg"
        },
        {
          title: "El Risas",
          year: 2019,
          image: "https://i.blogs.es/d0ea1e/joker-joaquin-phoenix/450_1000.jpg"
        },
        {
          title: "Spiderman",
          year: 2000,
          image:
            "https://www.infobae.com/new-resizer/XkfkqIeQ16c2-lbWKdS7OFcbWoY=/750x0/filters:quality(100)/s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/11/16142656/Spiderman.jpg"
        }
      ]
    };
  },
  methods: {
    mostrarFavorita(favorita){
      this.favorita = favorita;
    }
  },
  computed: {
    peliculasMayuscula(){
      var peliculasModificadas = this.peliculas;
      console.log(peliculasModificadas);
      for(var i = 0 ; i < peliculasModificadas.length ; i++){
          peliculasModificadas[i].title = peliculasModificadas[i].title.toUpperCase();
      }
      return peliculasModificadas;
    },
    mostrarDatos(){
      return '<strong>Nombre:</strong> ' + this.nombre + '<hr/><strong>Sitio Web:</strong> ' + this.web;
    }
  },
  filters: {
    mayusculas(value){
      return value.toUpperCase();
    },

    concatYear(value){
      var date = new Date();
      return value + ' - ' + date.getFullYear();
    }
  }
};
</script>

// AprendiendoAngular/src/app/components/peliculas/peliculas.component.ts
import { Component, OnInit, DoCheck, OnDestroy } from '@angular/core';
import { Pelicula } from '../../models/pelicula';
@Component({
  selector: 'app-peliculas',
  templateUrl: './peliculas.component.html',
  styleUrls: ['./peliculas.component.css']
})
export class PeliculasComponent implements OnInit, DoCheck, OnDestroy {
  public peliculas: Pelicula[];
  public titulo: String;
  public peliculaFavorita: Pelicula;

  constructor() { 
    console.log("Contructor Lanzado");
    this.titulo = "Componente peliculas";
    this.peliculas = [
      new Pelicula("Spiderman", 2002, "https://www.infobae.com/new-resizer/XkfkqIeQ16c2-lbWKdS7OFcbWoY=/750x0/filters:quality(100)/s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/11/16142656/Spiderman.jpg"),
      new Pelicula("Los vengadores", 2019, "https://i.blogs.es/876f04/los-vengadores-4/450_1000.jpg"),
      new Pelicula("El risas", 2019, "https://i.blogs.es/d0ea1e/joker-joaquin-phoenix/450_1000.jpg"),
      new Pelicula("Harry Potter y el Caliz de fuego", 2019, "https://i.ytimg.com/vi/CKt0PQFECfs/maxresdefault.jpg"),
    ]
  }

  public favorita: Pelicula;

  ngOnInit() {
    console.log("Evento onInit lanzado");
  }

  ngDoCheck() {
    console.log("DoCheck lanzado");
  }

  ngOnDestroy() {
    console.log("El componente se va a eliminar");
  }

  cambiarTitulo(){
    this.titulo = this.titulo + "Cambiado";
  }

  mostrarFavorita(pelicula){
    this.peliculaFavorita = pelicula;
  }
}

<app-slider [nombre]="'Peliculas'" [size]="'small'"></app-slider>

<div class="center">
    <section id="content">
        <h2 class="subheader">Peliculas</h2>
        <p>{{ titulo }}</p>
        <button (click)="cambiarTitulo()">Pulsame</button>


        <hr />

        <div *ngIf="peliculas.length <= 3">
            <p>No hay muchas peliculas</p>
        </div>

        <div *ngIf="peliculas.length > 3">
            <p>Hay muchas peliculas</p>
        </div>
        <h2 class="subheader">Numero de peliculas: {{peliculas.length}}</h2>
        
        <p class="subheader" *ngIf="peliculaFavorita">Pelicula favorita: {{peliculaFavorita.title}}</p>
        <h2 class="subheader">Peliculas</h2>
        <div id="articles" *ngIf="peliculas">
            <div *ngFor="let pelicula of peliculas; let i = index;">
                <app-pelicula [pelicula]="pelicula" (marcarFavorita)="mostrarFavorita(pelicula)"></app-pelicula>
            </div>
        </div>
    </section>

    <app-sidebar></app-sidebar>
</div>
